---
- name: Set up configuration parameters 1/2
  set_fact: mongodb_major_minor_version=v{{mongodb_version[:3]}} # the 'v' is necessary due to Ansible's number autoconversion quirks

- name: Set up configuration parameters 2/2
  set_fact:
    mongodb_daemon_name: "{{mongodb_config['daemon']}}"

- include: install.deb.yml
  when: ansible_os_family == 'Debian' and mongodb_install

- include: install.xenial.yml
  when: ansible_os_family == 'Debian' and ansible_distribution_release == 'xenial'

- include: configure.yml
  when: mongodb_install

- include: docker.yml
  when: mongodb_docker

- include: mms-agent.yml
  when: mongodb_mms_api_key != ""
